# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_cpp <- function(names, black_box, test_treated_covs, test_control, test_treated, test_covs, test_treatments, test_outcomes, variation, n_req_matches, multiplier, user_PE_fit, user_PE_predict, PE_predict, bart_fit0, bart_fit1, fhat0, fhat1, expansion_variance_tmp, preprocess_cand, preprocess_covs, n_prune) {
    .Call(`_AHB_greedy_cpp`, names, black_box, test_treated_covs, test_control, test_treated, test_covs, test_treatments, test_outcomes, variation, n_req_matches, multiplier, user_PE_fit, user_PE_predict, PE_predict, bart_fit0, bart_fit1, fhat0, fhat1, expansion_variance_tmp, preprocess_cand, preprocess_covs, n_prune)
}

